## 히든레이어
- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측
#### 데이터 준비

In [2]:
Boston_file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(Boston_file_path)

In [6]:
print(boston.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [7]:
# 종속변수, 독립변수
independent_boston = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
dependent_boston = boston[['medv']]
print(independent_boston.shape, dependent_boston.shape)

(506, 13) (506, 1)


#### 모델의 구조 생성

In [9]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [10]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


#### 모델 학습하기(fit)

In [12]:
model.fit(independent_boston, dependent_boston, epochs=1000, verbose=0)
model.fit(independent_boston, dependent_boston, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2731
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 14.1418
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 14.3555
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 14.3724
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 14.0959
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2653
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 13.5218
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 13.1342
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 13.4080
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 13.7534


#### 모델 이용

In [13]:
print(model.predict(independent_boston[:5]))

[[30.437943]
 [20.457735]
 [31.355253]
 [31.076683]
 [27.627798]]


In [14]:
print(dependent_boston[:5])

   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [15]:
# 모델의 수식 확인
print(model.get_weights())

[array([[ 1.03804231e-01,  9.95695591e-02, -1.13052666e-01,
         7.64460146e-01,  1.99860647e-01,  6.08206056e-02,
         2.56475389e-01,  8.10620263e-02,  3.56821954e-01,
         2.42122367e-01],
       [-4.60735589e-01, -4.10892218e-01,  6.73777461e-02,
        -4.48125862e-02,  7.45252788e-01, -5.85666485e-02,
         8.62549171e-02,  1.77572146e-02, -4.28631395e-01,
        -2.79666603e-01],
       [-2.50149488e-01,  4.27654564e-01,  2.44926155e-01,
        -4.12203938e-01,  1.14641398e-01, -9.41315070e-02,
        -6.08996451e-01, -1.57734025e-02, -2.36057132e-01,
        -4.02231842e-01],
       [ 2.65647948e-01,  9.26375389e-02,  3.90347004e-01,
        -1.65362680e+00,  9.41646755e-01,  1.41074300e+00,
         4.86716181e-01,  6.21140718e-01,  3.25928330e-01,
        -2.16786885e+00],
       [ 3.11630011e-01,  9.28791165e-02, -2.81456172e-01,
         7.79973209e-01, -1.21421134e+00,  2.93169498e-01,
        -1.25405967e+00,  2.25108579e-01, -1.30060524e-01,
        -4

## 아이리스 품종 분류

In [16]:
iris_file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(iris_file_path)

In [17]:
# onehot-encoding
iris = pd.get_dummies(iris)

In [18]:
print(iris.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [19]:
# 종속변수, 독립변수
independent_iris = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent_iris = iris[['품종_setosa', '품종_versicolor','품종_virginica']]
print(independent_iris.shape, dependent_iris)

(150, 4)      품종_setosa  품종_versicolor  품종_virginica
0            1              0             0
1            1              0             0
2            1              0             0
3            1              0             0
4            1              0             0
..         ...            ...           ...
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

[150 rows x 3 columns]


#### 모델의 구조 생성

In [20]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [21]:
# 모델 구조 확인
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


#### 데이터로 모델 학습(fit)

In [22]:
model.fit(independent_iris, dependent_iris, epochs=100, verbose=0)
model.fit(independent_iris, dependent_iris, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0751 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0748 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0746 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0764 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0755 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0761 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0738 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0731 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0777 - accuracy: 0.9867


#### 모델 이용

In [24]:
print(model.predict(independent_iris[:5]))

[[9.99991417e-01 3.20289064e-06 5.35615482e-06]
 [9.99968529e-01 1.64278281e-05 1.50067162e-05]
 [9.99971867e-01 1.26553687e-05 1.54669578e-05]
 [9.99850750e-01 1.01132304e-04 4.81813331e-05]
 [9.99989033e-01 4.29854254e-06 6.66912638e-06]]


In [25]:
print(dependent_iris[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
