## 아이리스 품종 분류
- git hub csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

### 데이터 준비

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [5]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

##### onehot-encoding : 범주형데이터를 0과 1로 바꿔주는 것

In [6]:
# onehot-encoding
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [7]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [11]:
# 종속변수, 독립변수
independent_variables = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]   # 독립변수
dependent_variables = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]   # 종속변수
print(independent_variables.shape, dependent_variables.shape)

(150, 4) (150, 3)


### 모델 구조 생성

In [13]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

### 데이터 학습

In [14]:
model.fit(independent_variables, dependent_variables, epochs=1000, verbose=0)
model.fit(independent_variables, dependent_variables, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1588 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1590 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1589 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1585 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1582 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1581 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1583 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1577 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1578 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1578 - accuracy: 0.9667


### 모델 이용

In [19]:
# 맨 처음 데이터 5개
model.predict(independent_variables[:5])

array([[9.9874425e-01, 1.2556547e-03, 7.3577937e-08],
       [9.9583769e-01, 4.1616186e-03, 6.6456505e-07],
       [9.9783784e-01, 2.1619170e-03, 2.4946775e-07],
       [9.9441516e-01, 5.5837920e-03, 1.0672413e-06],
       [9.9892884e-01, 1.0711306e-03, 5.6936919e-08]], dtype=float32)

In [16]:
print(dependent_variables[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [17]:
# 맨 마지막 5개
print(model.predict(independent_variables[-5:]))

[[1.0610321e-06 1.0552862e-01 8.9447027e-01]
 [2.2956071e-06 1.6203174e-01 8.3796597e-01]
 [4.1781786e-06 2.2329393e-01 7.7670187e-01]
 [1.0107401e-06 1.1095884e-01 8.8904017e-01]
 [8.9729620e-06 2.9602173e-01 7.0396930e-01]]


In [20]:
print(dependent_variables[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [22]:
# 학습한 가중치( weights & bias 출력)
print(model.get_weights())

[array([[ 0.38590038, -0.19341403, -0.9294877 ],
       [ 2.4152122 ,  0.2446155 , -1.4660366 ],
       [-3.4636214 , -0.07703817,  1.2227473 ],
       [-3.2709322 , -0.81430084,  2.6453562 ]], dtype=float32), array([ 2.1513436,  0.7915512, -1.7236451], dtype=float32)]
